
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubsznmwwzgzsssulpsdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVic3pubXd3emd6c3NzdWxwc2RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzQwMDgsImV4cCI6MjA1OTk1MDAwOH0.uYH-6_ZBl0a_knWWonWbnE0iGnClT84sUVtPNTV7j9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
